"""
Django settings for PGManagement project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-development-secret-key-change-this'
)

DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = []

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pg_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PGManagement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PGManagement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

ADMIN_SITE_HEADER = "Paying Guest Management System"
ADMIN_SITE_TITLE = "PG Management Admin"
ADMIN_INDEX_TITLE = "Welcome to PG Management System"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



DEFAULT_FROM_EMAIL = 'noreply@pgmanagement.local'

JAZZMIN_SETTINGS = {

    # ================= BRANDING =================

    "site_title": "PG Management Admin",

    "site_header": "PG Management System",

    "site_brand": "PG Management",

    "welcome_sign": "Welcome to PG Management Admin Panel",

    "copyright": "PG Management System © 2026",


    # ================= LOGO =================

    "site_logo": None,

    "login_logo": None,

    "site_icon": None,


    # ================= TOP MENU =================

    "topmenu_links": [

        {
            "name": "Dashboard",
            "url": "admin:index",
            "permissions": ["auth.view_user"],
        },

        {
            "name": "Website",
            "url": "/",
            "new_window": False,
        },

    ],


    # ================= USER MENU =================

    "usermenu_links": [

        {
            "name": "Website",
            "url": "/",
            "new_window": False,
        },

    ],


    # ================= SIDEBAR =================

    "show_sidebar": True,

    "navigation_expanded": True,

    "hide_apps": [],

    "hide_models": [],


    # ================= SIDEBAR ICONS =================

    "icons": {

        "auth": "fas fa-users-cog",

        "auth.user": "fas fa-user",

        "auth.group": "fas fa-user-shield",

        "pg_app": "fas fa-building",

        "pg_app.pg": "fas fa-building",

        "pg_app.room": "fas fa-door-open",

        "pg_app.bed": "fas fa-bed",

        "pg_app.tenant": "fas fa-users",

        "pg_app.payment": "fas fa-money-bill-wave",

        "pg_app.complaint": "fas fa-exclamation-circle",

        "pg_app.notice": "fas fa-bullhorn",

        "pg_app.attendance": "fas fa-calendar-check",

    },


    # ================= UI OPTIONS =================

    "show_ui_builder": True,

    "changeform_format": "horizontal_tabs",

    "changeform_format_overrides": {},


    # ================= LANGUAGE =================

    "language_chooser": False,


    # ================= CUSTOM LINKS =================

    "custom_links": {},


    # ================= SEARCH =================

    "search_model": [
        "auth.User",
        "pg_app.PG",
        "pg_app.Room",
        "pg_app.Bed",
        "pg_app.Tenant",
        "pg_app.Payment",
        "pg_app.Complaint",
        "pg_app.Notice",
        "pg_app.Attendance",
    ],

}

JAZZMIN_UI_TWEAKS = {

    "navbar_small_text": False,

    "footer_small_text": False,

    "body_small_text": False,

    "brand_small_text": False,

    "brand_colour": "primary",

    "accent": "primary",

    "navbar": "navbar-dark",

    "no_navbar_border": False,

    "navbar_fixed": True,

    "layout_boxed": False,

    "footer_fixed": False,

    "sidebar_fixed": True,

    "sidebar": "sidebar-dark-primary",

    "sidebar_nav_small_text": False,

    "sidebar_disable_expand": False,

    "sidebar_nav_child_indent": True,

    "sidebar_nav_compact_style": False,

    "sidebar_nav_legacy_style": False,

    "sidebar_nav_flat_style": True,

    "theme": "default",

    "dark_mode_theme": "darkly",

}