# Generated by Django 6.1.1 on 2026-10-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_profiles/'),
        ),
    ]
