# Generated by Django 6.1.1 on 2026-10-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0004_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, default=None, editable=False, max_length=100, null=True),
        ),
    ]
