# Generated by Django 6.1.1 on 2026-10-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pg_app', '0005_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
